import numpy
import pybullet as p

# setting up the gravity
GRAVITY_X = 0
GRAVITY_Y = 0
GRAVITY_Z = -981

# steps of simulation
SIMULATION_STEPS = 10000

# time between simuation steps [s]
TIME_BETWEEN_STEPS = 1/240

# parameters for all motors
CONTROL_MODE = p.POSITION_CONTROL
MAX_FORCE = 50

# Coefficient for friction of objects within the simulation
LATERAL_FRICTION_COEFFICIENT = 1000

# Limits of the Joints
UPPER_LIMIT_CARPUT_PROTHORAX = 0
LOWER_LIMIT_CARPUT_PROTHORAX = 0
UPPER_LIMIT_PROTHORAX_MESOTHORAX = 0
LOWER_LIMIT_PROTHORAX_MESOTHORAX = 0
UPPER_LIMIT_MESOTHORAX_METATHORAX = 0
LOWER_LIMIT_MESOTHORAX_METATHORAX = 0
UPPER_LIMIT_METATHORAX_ABDOMEN_3 = 0
LOWER_LIMIT_METATHORAX_ABDOMEN_3 = 0
UPPER_LIMIT_ABDOMEN_3_ABDOMEN_2 = 0
LOWER_LIMIT_ABDOMEN_3_ABDOMEN_2 = 0
UPPER_LIMIT_ABDOMEN_2_ABDOMEN_1 = 0
LOWER_LIMIT_ABDOMEN_2_ABDOMEN_1 = 0
UPPER_LIMIT_ABDOMEN_1_ABDOMEN_0 = 0
LOWER_LIMIT_ABDOMEN_1_ABDOMEN_0 = 0
UPPER_LIMIT_FL_CT_L = 2
LOWER_LIMIT_FL_CT_L = -2
UPPER_LIMIT_FL_CT_R = 2
LOWER_LIMIT_FL_CT_R = -2
UPPER_LIMIT_ML_CT_L = 2
LOWER_LIMIT_ML_CT_L = -2
UPPER_LIMIT_ML_CT_R = 2
LOWER_LIMIT_ML_CT_R = -2
UPPER_LIMIT_HL_CT_L = 2
LOWER_LIMIT_HL_CT_L = -2
UPPER_LIMIT_HL_CT_R = 2
LOWER_LIMIT_HL_CT_R = -2
UPPER_LIMIT_FL_FEMUR_L = 2
LOWER_LIMIT_FL_FEMUR_L = -2
UPPER_LIMIT_FL_FEMUR_R = 2
LOWER_LIMIT_FL_FEMUR_R = -2
UPPER_LIMIT_ML_FEMUR_L = 2
LOWER_LIMIT_ML_FEMUR_L = -2
UPPER_LIMIT_ML_FEMUR_R = 2
LOWER_LIMIT_ML_FEMUR_R = -2
UPPER_LIMIT_HL_FEMUR_L = 2
LOWER_LIMIT_HL_FEMUR_L = -2
UPPER_LIMIT_HL_FEMUR_R = 2
LOWER_LIMIT_HL_FEMUR_R = -2
UPPER_LIMIT_FL_TIBIA_L = 2
LOWER_LIMIT_FL_TIBIA_L = -2
UPPER_LIMIT_FL_TIBIA_R = 2
LOWER_LIMIT_FL_TIBIA_R = -2
UPPER_LIMIT_ML_TIBIA_L = 2
LOWER_LIMIT_ML_TIBIA_L = -2
UPPER_LIMIT_ML_TIBIA_R = 2
LOWER_LIMIT_ML_TIBIA_R = -2
UPPER_LIMIT_HL_TIBIA_L = 2
LOWER_LIMIT_HL_TIBIA_L = -2
UPPER_LIMIT_HL_TIBIA_R = 2
LOWER_LIMIT_HL_TIBIA_R = -2
UPPER_LIMIT_FL_TARSUS_L = 2
LOWER_LIMIT_FL_TARSUS_L = -2
UPPER_LIMIT_FL_TARSUS_R = 2
LOWER_LIMIT_FL_TARSUS_R = -2
UPPER_LIMIT_ML_TARSUS_L = 2
LOWER_LIMIT_ML_TARSUS_L = -2
UPPER_LIMIT_ML_TARSUS_R = 2
LOWER_LIMIT_ML_TARSUS_R = -2
UPPER_LIMIT_HL_TARSUS_L = 2
LOWER_LIMIT_HL_TARSUS_L = -2
UPPER_LIMIT_HL_TARSUS_R = 2
LOWER_LIMIT_HL_TARSUS_R = -2